backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "catalog"
    label: "Κατάλογος"
    files:
      - label: "Όλα τα Γυαλιά"
        name: "products"
        file: "data/products.json"
        fields:
          - label: "Λίστα Γυαλιών"
            name: "items"
            widget: "list"
            fields:
              - { label: "Όνομα Μοντέλου", name: "name", widget: "string" }
              - { label: "Τιμή (π.χ. 149.99 €)", name: "price", widget: "string" }
              - { label: "Φωτογραφία", name: "img", widget: "image" }
              - { label: "Unique ID", name: "id", widget: "string" }
              - { label: "Brand", name: "brand", widget: "string" }